version: '3.3'

services:

  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe        
    container_name: oracledatabase    
    ports:    
      - 1521:1521
    environment:
      ORACLE_PWD: root
      

